spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/carservice?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    username: "root"
    password:  "mintajzporem"
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/" 