eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/" 

spring:
    application:
            name: research-service
            
allegro:
    offers:
        uri: "https://api.allegro.pl/offers/listing"
        carsId:
            param: "category.id=4029"

