spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/carservice?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    username: "root"
    password:  "mintajzporem"
  jpa:
    hibernate:
      ddl-auto: update
